Update config.toml
Update the config.toml back to original setting as it did not fix the following error:
---start---
Run hugo --minify
Error: module "https://github.com/jakewies/hugo-theme-codex" not found; either add it as a Hugo Module or store it in "/home/runner/work/bis402.github.io/bis402.github.io/themes".: module does not exist
Total in 0 ms
Error: Process completed with exit code 255.
---end---
The previous changes to the config.toml did not correct the issue.